### ISSUE TITLE
volto-introduction-block not registered as package in package.json

### ISSUE THREAD

**Issue by fredvd** [plone/plone.de#8]
```
Error: ENOENT: no such file or directory, lstat '/Users/fred/plone/plone.de/frontend/src/addons/volto-introduction-block'
    at Object.realpathSync (node:fs:2533:7)
    at /Users/fred/plone/plone.de/frontend/node_modules/@plone/volto/razzle.config.js:287:20
    at Array.forEach (<anonymous>)
    at defaultModify (/Users/fred/plone/plone.de/frontend/node_modules/@plone/volto/razzle.config.js:286:19)
    at modifyWebpackConfig (/Users/fred/plone/plone.de/frontend/node_modules/@plone/volto/razzle.config.js:381:27)
    at /Users/fred/plone/plone.de/frontend/node_modules/razzle/config/createConfigAsync.js:1069:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/fred/plone/plone.de/frontend/src/addons/volto-introduction-block'
}
```

**Comment by fredvd** [comment]
Ah, I should run make install to have volto-introduction-block added from the mrs-developer configuration as a src package.
